# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-23 16:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_loci', '0002_auto_20171122_1713'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='objectlocation',
            name='type',
        ),
        migrations.AlterField(
            model_name='location',
            name='name',
            field=models.CharField(help_text='A descriptive name of the location (building name, company name, etc.)', max_length=75, verbose_name='name'),
        ),
    ]
