# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-13 11:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('django_loci', '0002_auto_20171113_1235'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='objectlocation',
            unique_together=set([('content_type', 'object_id')]),
        ),
    ]
