# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-23 17:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_loci', '0003_auto_20171123_1722'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='is_mobile',
            field=models.BooleanField(db_index=True, default=False, help_text='is this location a moving object?', verbose_name='is mobile?'),
        ),
    ]
